title: "UTSRWR"
description: "Jejak digital pemikiran, rasa, dan pengalaman â€” ditulis apa adanya."
author: "Wildan Hidayat"
baseurl: "" 
url: "https://utsrwr.github.io"
markdown: kramdown
theme: null

timezone: Asia/Jakarta

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
